docker:
  image: gcr.io/repo-automation-bots/owlbot-nodejs:latest
copy-dirs:
  - source: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/src/*
    dest: /src
    strip-prefix: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/src
  - source: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/protos/google/cloud/phishingprotection/*
    dest: /protos/google/cloud
    strip-prefix: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/protos/google/cloud/phishingprotection
  - source: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/test/*
    dest: /test
    strip-prefix: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/test
  - source: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/system-test/*
    dest: /
    strip-prefix: /google/cloud/phishingprotection/*/phishingprotection-*-nodejs/
